project_id = "rcrpqdhfawtpjicttgvx"

[functions.docsumo-extract]
verify_jwt = false

[functions.openai-analysis]
verify_jwt = true

[functions.get-postgrid-key]
verify_jwt = true

[functions.webhooks-browseai]
verify_jwt = false

[functions.smart-credit-import-start]
verify_jwt = true

[functions.smart-credit-import-stream]
verify_jwt = true

[functions.smart-credit-connect-and-start]
verify_jwt = true

[functions.smart-credit-webhook]
verify_jwt = false

[functions.smart-credit-import-health]
verify_jwt = true

[functions.smart-credit-summary]
verify_jwt = true

[functions.smart-credit-items]
verify_jwt = true
