
project_id = "rcrpqdhfawtpjicttgvx"

[functions.adobe-pdf-extract]
verify_jwt = false

[functions.enhanced-pdf-extract]
verify_jwt = false

[functions.textract-extract]
verify_jwt = false

[functions.openai-analysis]
verify_jwt = true

[functions.get-postgrid-key]
verify_jwt = true
