project_id = "rcrpqdhfawtpjicttgvx"

[functions.docsumo-extract]
verify_jwt = false

[functions.openai-analysis]
verify_jwt = true

[functions.get-postgrid-key]
verify_jwt = true

[functions.webhooks-browseai]
verify_jwt = false

[functions.smart-credit-import-start]
verify_jwt = true

[functions.smart-credit-import-stream]
verify_jwt = false

[functions.smart-credit-connect-and-start]
verify_jwt = true

[functions.smart-credit-webhook]
verify_jwt = false

[functions.smart-credit-import-health]
verify_jwt = true

[functions.smart-credit-summary]
verify_jwt = true

[functions.smart-credit-items]
verify_jwt = true

[functions.browseai-start]
verify_jwt = false

[functions.browseai-status]
verify_jwt = false

[functions.credit-report-latest]
verify_jwt = true

[functions.credit-report-latest-raw]
verify_jwt = true

[functions.credit-report-latest-debug]
verify_jwt = true

[functions.credit-report-ingest]
verify_jwt = false

[functions.ingest-credit-round]
verify_jwt = false

[functions.credit-rounds-delete]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = true
